### ISSUE TITLE
Get back to kases that I don't want in my "inbox"

### ISSUE THREAD

**Issue by bigtiger** [beflagrant/kasey#10]
I have a kase that is currently responded to and I don't want to see in my queue. Case 0 on [flagrant-contact](https://flagrant-contact.herokuapp.com/kasey/kases) is one example. I want to "archive" and if they ever respond again I want it back in my inbox.

I now understand that Destroy is a "soft delete", in the Parler of our time 😂, there is not however any way for me to navigate to see those kases.

**Comment by bvandgrift** [comment]
added route: `/kasey/kases/closed`, along with a link at the bottom of the index page that will display 'show closed cases' or 'show active cases' depending on which page you're viewing.
