### ISSUE TITLE
Case cannot be destroyed without being viewed

### ISSUE THREAD

**Issue by bigtiger** [beflagrant/kasey#6]
Our AASM configuration does not allow the transition from `open` to `closed`.

I think that's probably OK. The experience could be improved. Currently it just throws and error.

Options, in addition whatever you think, would be:

- Only show the destroy button when the case state is not `open`.
- Put the Destroy on the show page for the case.

**Comment by bvandgrift** [comment]
I've changed the Destroy button to 'Close', since that's the actual action; button no longer shows up if case is :open

**Comment by bvandgrift** [comment]
bumped version to 0.1.1
